### PR TITLE
chore(deployment): fix diamond deploy script

### LINKED ISSUE #585: `DiamondInAll.ts` broken syntax with merge
> @zgorizzo69 btw I'm running prettier on everything and noticed that this commit super broke DiamondInAll.ts you should check again.

https://github.com/ubiquity/ubiquity-dollar/commit/36de2d0c274b13c86334c86b7c8285d9aa5729c1#r102057720

image

### PR DESCRIPTION
**Pull request by zgorizzo69**
Resolves #585

`DiamondInit` is a special contract that is kind of a constructor for the diamond

As it is now the diamond Init contract is way to gas heavy to be deployed 
in this pr I removed some token's deployment that were happening inside the diamond init.

Note that  Access control is inside the diamond  and each token has the diamond address to be able to call access control logic . 

So we have to first deploy the diamond and then the tokens because token's constructor needs the diamond address.

### CODE REVIEW

File: packages/contracts/scripts/deploy/manager/DiamondDeployHelper.ts [hunk 1]
```diff
@@ -24,8 +24,9 @@ export async function getSelectorsFromFacet(contractName: string, artifactFolder
   return selectors;
 }
 
-export function getContractInstance(contractName: string, account?: any, artifactFolderPath = "../../../out") {
+export function getContractInstance(contractName: string, account?: ethers.Signer | undefined, artifactFolderPath = "../../../out") {
```
Comment (0x4007) [inline packages/contracts/scripts/deploy/manager/DiamondDeployHelper.ts]:
```suggestion
export function getContractInstance(contractName: string, account?: ethers.Signer, artifactFolderPath = "../../../out") {
```

Code smell. Consider checking the parameter before or after its passed in.

File: packages/contracts/scripts/deploy/manager/DiamondInAll.ts [hunk 2]
```diff
@@ -10,258 +10,255 @@ import { Networks } from "../../shared/constants/networks";
...
+  name: string;
+  network: string;
+  rpcUrl: string;
+  privateKey: string;
+  contractInstance: string;
+  constructorArguments?: [DiamondArgs, cutType[]];
+  etherscanApiKey?: string;
 };
 
 const create = async (args: ForgeArguments): Promise<{ result: DeploymentResult | undefined; stderr: string }> => {
```
Comment (0x4007) [inline packages/contracts/scripts/deploy/manager/DiamondInAll.ts:40]:
```suggestion
const create = async (args: ForgeArguments): Promise<{ result: DeploymentResult; stderr: string }> => {
```

File: packages/contracts/scripts/deploy/manager/DiamondInAll.ts [hunk 3]
```diff
@@ -10,258 +10,255 @@ import { Networks } from "../../shared/constants/networks";
...
-        const diamondArgs = args.constructorArguments[0];
-        const diamondCut = args.constructorArguments[1];
+  let flattenConstructorArgs = `"(`;
+  let prepareCmd: string;
+  if (args.constructorArguments) {
+    const diamondArgs = args.constructorArguments[0];
+    const diamondCut = args.constructorArguments[1];
 
-    flattenConstructorArgs += `${diamondArgs.owner},${diamondArgs.init},${diamondArgs.initCalldata})\" \"[`;
+    flattenConstructorArgs += `${diamondArgs.owner},${diamondArgs.init},${diamondArgs.initCalldata})" "[`;
```
Comment (0x4007) [inline packages/contracts/scripts/deploy/manager/DiamondInAll.ts]: When concatenating strings in JavaScript, I highly recommend not using `+=` because if something else other than a string slips in it messes everything up. For quick concatenations, I use `String.concat(String)`. For long concatenatons, consider adding the strings into an array, and then calling Array.join(`,`);

```javascript
[ flattenConstructorArgs, diamondArgs.owner, diamondArgs.init, diamondArgs.initCalldata ].join(',')
```

Something like that.

File: packages/contracts/scripts/deploy/manager/DiamondDeployHelper.ts [hunk 4]
```diff
@@ -5,15 +5,15 @@ export const FacetCutAction = { Add: 0, Replace: 1, Remove: 2 };
 
 export async function getSelectorsFromFacet(contractName: string, artifactFolderPath = "../../../out") {
   const contractFilePath = path.join(artifactFolderPath, `${contractName}.sol`, `${contractName}.json`);
+  // eslint-disable-next-line @typescript-eslint/no-var-requires
   const contractArtifact = require(contractFilePath);
```
Comment (0x4007) [inline packages/contracts/scripts/deploy/manager/DiamondDeployHelper.ts]: Why not use import?

File: packages/contracts/scripts/deploy/manager/DiamondDeployHelper.ts [hunk 5]
```diff
@@ -24,8 +24,9 @@ export async function getSelectorsFromFacet(contractName: string, artifactFolder
   return selectors;
 }
 
-export function getContractInstance(contractName: string, account?: any, artifactFolderPath = "../../../out") {
+export function getContractInstance(contractName: string, account?: ethers.Signer | undefined, artifactFolderPath = "../../../out") {
   const contractFilePath = path.join(artifactFolderPath, `${contractName}.sol`, `${contractName}.json`);
+  // eslint-disable-next-line @typescript-eslint/no-var-requires
   const contractArtifact = require(contractFilePath);
```
Comment (0x4007) [inline packages/contracts/scripts/deploy/manager/DiamondDeployHelper.ts]: await import

File: packages/contracts/scripts/deploy/manager/PrintSelectors.ts [hunk 6]
```diff
@@ -12,15 +12,15 @@ if (args.length != 1) {
 
 async function printSelectors(contractName: string, artifactFolderPath = "../../../out") {
   const contractFilePath = path.join(artifactFolderPath, `${contractName}.sol`, `${contractName}.json`);
+  // eslint-disable-next-line @typescript-eslint/no-var-requires
   const contractArtifact = require(contractFilePath);
```
Comment (0x4007) [inline packages/contracts/scripts/deploy/manager/PrintSelectors.ts]: await import

File: packages/contracts/scripts/deploy/manager/DiamondInAll.ts (hunk 3 above)
Comment (zgorizzo69) [reply packages/contracts/scripts/deploy/manager/DiamondInAll.ts]: I was just fixing a lint error but I agree and would even say don't use concat just use tild `

File: packages/contracts/scripts/deploy/manager/DiamondInAll.ts (hunk 2 above)
Comment (zgorizzo69) [reply packages/contracts/scripts/deploy/manager/DiamondInAll.ts:40]: if we stdout is null then result will be undefined check line 95 so we need that return type

File: packages/contracts/scripts/deploy/manager/DiamondInAll.ts (hunk 3 above)
Comment (zgorizzo69) [reply packages/contracts/scripts/deploy/manager/DiamondInAll.ts]: done

File: packages/contracts/scripts/deploy/manager/DiamondDeployHelper.ts (hunk 4 above)
Comment (zgorizzo69) [reply packages/contracts/scripts/deploy/manager/DiamondDeployHelper.ts]: done

File: packages/contracts/scripts/deploy/manager/DiamondDeployHelper.ts (hunk 5 above)
Comment (zgorizzo69) [reply packages/contracts/scripts/deploy/manager/DiamondDeployHelper.ts]: done

File: packages/contracts/scripts/deploy/manager/PrintSelectors.ts (hunk 6 above)
Comment (zgorizzo69) [reply packages/contracts/scripts/deploy/manager/PrintSelectors.ts]: done refactoring old code with import !

File: packages/contracts/scripts/deploy/manager/DiamondInAll.ts (hunk 2 above)
Comment (0x4007) [reply packages/contracts/scripts/deploy/manager/DiamondInAll.ts:40]: I'm unsure what you mean by line 95 its just a regex.

Comment (zgorizzo69) [reply packages/contracts/scripts/deploy/manager/DiamondInAll.ts:40]: ok 94 ..the point is we need to be able to return undefined

Comment (0x4007) [reply packages/contracts/scripts/deploy/manager/DiamondInAll.ts:40]: Doesn't it make more sense to return a non zero exit code, or at least null? That signals intent unlike undefined.

Comment (zgorizzo69) [reply packages/contracts/scripts/deploy/manager/DiamondInAll.ts:40]: It makes sense to return undefined as the variable result is not even set if stdout is null

**Comment by 0x4007** [comment]
I guess we need to upgrade our conventional commits CI to support GitHub webapp commit messages.
