### PR TITLE
fix: show USDT balance in footer

### LINKED ISSUE #323: Tether Balance Not Rendering Correctly in Inventory
For once I have a Tether balance and noticed that its rendering as `0 USDT` in the Inventory even though I have exactly `1000 USDT`

image

image

### PR DESCRIPTION
**Pull request by ryzhak**
PR for https://github.com/ubiquity/ubiquity-dollar/issues/323

### CODE REVIEW

File: packages/dapp/components/layout/Inventory.tsx [hunk 1]
```diff
@@ -50,7 +50,7 @@ const Inventory = () => {
 
   function showIfBalanceExists(key: keyof Balances | keyof typeof namedContracts, name: keyof typeof tokenSvg, id: string) {
     const usdcFix = function () {
-      if (key == "usdc") return 6;
+      if (key == "usdc" || key == "usdt") return 6;
```
Comment (cuddle-dev) [inline packages/dapp/components/layout/Inventory.tsx:53]: usdc/usdt decimals vary per chain for example the decimals of usdc is 18 on bnb chain. so it will not work on other chains.

**Review by cuddle-dev — CHANGES_REQUESTED** [review]

File: packages/dapp/components/layout/Inventory.tsx (hunk 1 above)
Comment (0x4007) [reply packages/dapp/components/layout/Inventory.tsx:53]: I had no idea but is the correct solution to check the amount of decimals then render that amount of decimals every time?

I also think that this solution is fine for our purposes because we don't plan to support bsc. 

Basically only possibly roll ups that settle on Ethereum.

**Comment by ryzhak** [comment]
so should I change smth in this PR?

**Comment by 0x4007** [comment]
I think its fine don't worry about it.

> so should I change smth in this PR?
