### PR TITLE
Fix Vercel deployment

### LINKED ISSUE #99: Vercel Build Process
## Overview

Vercel fails to build when deploying. When we refactored everything into a monorepo we also significantly automated the build process. Unfortunately this new build process does not seem to work for Vercel.

## Findings

* Please login to the @ubiquity-vercel account, then login to Vercel in order to access our staging environment.
* Vercel is programmed to run `yarn run vercel-build` automatically; so I hooked in a debugging script for this task `./build-scripts/vercel-build.sh`
* This debugging script replicates the build process, but in series instead of in parallel to make it easier to see what's happening.
* I suggest you debug the build process by editing this shell script, and directly pushing to the `@ubiquity-vercel/ubiquity-dollar-staging` repository.
* It appears that on my local machine it understands to load `hardhat` and `next` from the `node_modules` whereas Vercel asserts the following:

```
[19:20:27.730] error Command "hardhat" not found.
```
and
```
[19:21:40.104] error Command "next" not found.
```

## Vercel Log

The full Vercel log is below. 

```
[19:19:35.220] Cloning github.com/ubiquity-vercel/ubiquity-dollar-staging (Branch: main, Commit: 8f6d71b)
[19:19:36.004] Cloning completed: 783.321ms
[19:19:36.396] Installing build runtime...
[19:19:39.607] Build runtime installed: 3.211s
[19:19:40.787] Looking up build cache...
[19:19:41.050] Build Cache not found
[19:19:41.250] Installing dependencies...
[19:19:41.492] yarn install v1.22.17
[19:19:41.560] [1/4] Resolving packages...
[19:19:41.903] [2/4] Fetching packages...
[19:19:56.150] [3/4] Linking dependencies...
[19:19:56.156] warning "next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
[19:20:04.825] [4/4] Building fresh packages...
[19:20:05.186] $ husky install
[19:20:05.262] husky - Git hooks installed
[19:20:05.265] Done in 23.78s.
[19:20:05.287] Detected Next.js version: 11.1.4
[19:20:05.288] Running "yarn run vercel-build"
[19:20:05.560] yarn run v1.22.17
[19:20:05.586] $ ./build-scripts/vercel-build.sh
[19:20:05.602] 
[19:20:05.602] installing nft...
[19:20:05.602] 
[19:20:06.012] [1/4] Resolving packages...
[19:20:06.541] [2/4] Fetching packages...
[19:20:06.550] warning Pattern ["hardhat-deploy-ethers@^0.3.0-beta.13"] is trying to unpack in the same destination "/vercel/.cache/yarn/v6/npm-@nomiclabs-hardhat-ethers-0.3.0-beta.13-integrity/node_modules/@nomiclabs/hardhat-ethers" as pattern ["@nomiclabs/hardhat-ethers@npm:hardhat-deploy-ethers@^0.3.0-beta.13"]. This could result in non-deterministic behavior, skipping.
[19:20:26.827] [3/4] Linking dependencies...
[19:20:26.831] warning " > @nomiclabs/hardhat-waffle@2.0.2" has incorrect peer dependency "@nomiclabs/hardhat-ethers@^2.0.0".
[19:20:26.832] warning " > eslint-config-standard@16.0.3" has incorrect peer dependency "eslint@^7.12.1".
[19:20:26.832] warning " > eslint-config-standard@16.0.3" has incorrect peer dependency "eslint-plugin-promise@^4.2.1 || ^5.0.0".
[19:20:26.997] [4/4] Building fresh packages...
[19:20:27.077] 
[19:20:27.077] ...complete!
[19:20:27.077] 
[19:20:27.077] 
[19:20:27.077] building nft...
[19:20:27.077] 
[19:20:27.396] $ TS_NODE_TRANSPILE_ONLY=1 yarn hardhat compile
[19:20:27.730] error Command "hardhat" not found.
[19:20:27.730] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[19:20:27.754] error Command failed with exit code 1.
[19:20:27.754] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[19:20:27.767] 
[19:20:27.767] ...complete!
[19:20:27.767] 
[19:20:27.767] 
[19:20:27.767] installing dollar...
[19:20:27.767] 
[19:20:28.111] [1/4] Resolving packages...
[19:20:28.653] [2/4] Fetching packages...
[19:20:47.876] [3/4] Linking dependencies...
[19:20:47.880] warning " > @typechain/ethers-v5@9.0.0" has incorrect peer dependency "typechain@^7.0.0".
[19:21:16.430] [4/4] Building fresh packages...
[19:21:16.430] warning Ignored scripts due to flag.
[19:21:16.496] 
[19:21:16.496] ...complete!
[19:21:16.496] 
[19:21:16.496] 
[19:21:16.496] building dollar...
[19:21:16.496] 
[19:21:16.718] $ TS_NODE_TRANSPILE_ONLY=1 yarn hardhat compile
[19:21:16.962] $ /vercel/path0/contracts/dollar/node_modules/.bin/hardhat compile
[19:21:18.332] Tasks loading skipped until compilation artifacts are available
[19:21:23.225] Downloading compiler 0.8.3
[19:21:23.666] Compiling 87 files with 0.8.3
[19:21:31.863] Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
[19:21:31.864] --> @uniswap/v2-core/contracts/interfaces/IUniswapV2Factory.sol
[19:21:31.864] 
[19:21:31.864] 
[19:21:31.865] Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
[19:21:31.865] --> @uniswap/v2-core/contracts/interfaces/IUniswapV2Pair.sol
[19:21:31.865] 
[19:21:31.865] 
[19:21:31.866] Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
[19:21:31.866] --> @uniswap/v2-periphery/contracts/interfaces/IUniswapV2Router01.sol
[19:21:31.866] 
[19:21:31.866] 
[19:21:31.866] Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
[19:21:31.866] --> @uniswap/v2-periphery/contracts/interfaces/IUniswapV2Router02.sol
[19:21:31.866] 
[19:21:31.866] 
[19:21:31.866] Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
[19:21:31.866]   --> contracts/BondingFormulas.sol:38:9:
[19:21:31.866]    |
[19:21:31.867] 38 |         BondingShareV2.Bond memory _bond,
[19:21:31.867]    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[19:21:31.867] 
[19:21:31.867] 
[19:21:31.867] Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
[19:21:31.867]   --> contracts/BondingFormulas.sol:39:9:
[19:21:31.867]    |
[19:21:31.867] 39 |         uint256[2] memory _shareInfo,
[19:21:31.867]    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[19:21:31.867] 
[19:21:31.867] 
[19:21:31.867] Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
[19:21:31.867]   --> contracts/BondingFormulas.sol:53:9:
[19:21:31.868]    |
[19:21:31.868] 53 |         BondingShareV2.Bond memory _bond,
[19:21:31.868]    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[19:21:31.868] 
[19:21:31.868] 
[19:21:31.868] Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
[19:21:31.868]   --> contracts/BondingFormulas.sol:54:9:
[19:21:31.868]    |
[19:21:31.868] 54 |         uint256[2] memory _shareInfo,
[19:21:31.869]    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[19:21:31.869] 
[19:21:31.869] 
[19:21:33.468] Solidity compilation finished successfully
[19:21:33.558] Creating Typechain artifacts in directory artifacts/types for target ethers-v5
[19:21:39.838] Successfully generated Typechain artifacts!
[19:21:39.872] 
[19:21:39.873] ...complete!
[19:21:39.873] 
[19:21:39.873] 
[19:21:39.873] starting ui...
[19:21:39.873] 
[19:21:40.104] error Command "next" not found.
[19:21:40.104] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[19:21:40.110] 
[19:21:40.111] ...complete!
[19:21:40.111] 
[19:21:40.111] Done in 94.56s.
[19:21:40.121] Error: The file "/vercel/path0/.next/routes-manifest.json" couldn't be found. This is normally caused by a misconfiguration in your project.
[19:21:40.121] Please check the following, and reach out to support if you cannot resolve the problem:
[19:21:40.121]   1. If present, be sure your `build` script in "package.json" calls `next build`.  2. Navigate to your project's settings in the Vercel dashboard, and verify that the "Build Command" is not overridden, or that it calls `next build`.  3. Navigate to your project's settings in the Vercel dashboard, and verify that the "Output Directory" is not overridden. Note that `next export` does **not** require you change this setting, even if you customize the `next export` output directory. Learn More: https://err.sh/vercel/vercel/now-next-routes-manifest
```

### PR DESCRIPTION
**Pull request by Zequez**
There were many issues, it wasn't just Vercel after all.
The `next build` command had some issues too.
The first thing was an issue with the paths on package.json; they need to be "./contracts/whatever" instead of "contracts/whatever" otherwise they don't seem to work.
Then there were some issues with conflicting versions of tools between the ubiquistick and dollar repositories; the typings generated were miss-matching and some things weren't working.
And there were some prettier errors too; I just turned them into warnings for the time being; I'll clean up later, they have no effect on the functionalities anyway.
There were some issues with the type matching of ERC20-based tokens that I ended up having to force a type casting. It seemed to be something about the newest version of Typechain, because it used to work with the older version.
And there was an issue in the way we were importing and re-exporting the PriceStabilization page that made Next.js freak out.
Over time we should work on the warnings, because the deployment is full of warnings lol

Vercel build command: `yarn build`
Vercel install command: `yarn install && yarn install-env && yarn install-contracts`

Preview https://ubiquity-dollar-development-three.vercel.app

Should close #99

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -43,3 +43,5 @@ systemctl/ \*_/_.DS_Store
 typings
 *.log
 /abi/types/*
+/fixtures/contracts-addresses/*
+!/fixtures/contracts-addresses/.keep
```
Comment (0x4007) [inline .gitignore:47]: This is cool, never knew you can do this.

File: build-scripts/vercel-build.sh [hunk 2]
```diff
@@ -0,0 +1,41 @@
+#!/usr/bin/env bash
```
Comment (0x4007) [inline build-scripts/vercel-build.sh:1]: @Zequez we should probably deprecate this file now? I'm not sure if you're still using it, but running these processes in series will make the build far slower!

File: components/YieldFarming.tsx [hunk 3]
```diff
@@ -46,8 +47,8 @@ export const YieldFarmingContainer = ({ contracts, account, signer }: UserContex
       console.log(`Depositing: USDC ${usdc} | UBQ ${ubq} | uAD ${uad}`);
       if (
         (await ensureERC20Allowance("USDC", contracts.usdc, bigUsdc, signer, contracts.yieldProxy.address, 6)) &&
-        (await ensureERC20Allowance("UBQ", contracts.ugov, bigUbq, signer, contracts.yieldProxy.address)) &&
-        (await ensureERC20Allowance("uAD", contracts.uad, bigUad, signer, contracts.yieldProxy.address)) &&
+        (await ensureERC20Allowance("UBQ", (contracts.ugov as unknown) as ERC20, bigUbq, signer, contracts.yieldProxy.address)) &&
+        (await ensureERC20Allowance("uAD", (contracts.uad as unknown) as ERC20, bigUad, signer, contracts.yieldProxy.address)) &&
```
Comment (0x4007) [inline components/YieldFarming.tsx:51]: muh typings 😭

File: contracts/dollar/hardhat.config.ts [hunk 4]
```diff
@@ -28,9 +30,8 @@ const {
   API_KEY_COINMARKETCAP,
 } = process.env;
 
-const mnemonic = `${
-  MNEMONIC || "test test test test test test test test test test test junk"
-}`;
+const mnemonic = `${MNEMONIC || "test test test test test test test test test test test junk"
```
Comment (0x4007) [inline contracts/dollar/hardhat.config.ts:33]: We should delete the fallback, as I currently have this as part of the build process to render an `.env` file with this as the default value for `$MNEMONIC`

File: contracts/dollar/package.json [hunk 5]
```diff
@@ -71,17 +71,17 @@
...
     "@ethersproject/address": "^5.5.0",
     "@ethersproject/bytes": "^5.0.0",
-    "@ethersproject/contracts": "^5.5.0",
     "@ethersproject/hardware-wallets": "^5.5.0",
     "@ethersproject/networks": "^5.5.2",
     "@ethersproject/providers": "^5.5.3",
     "@ethersproject/solidity": "^5.5.0",
     "@lavamoat/allow-scripts": "^2.0.0",
-    "@nomiclabs/hardhat-ethers": "^2.0.5",
+    "@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers@^0.3.0-beta.13",
```
Comment (0x4007) [inline contracts/dollar/package.json:79]: lol wtf

File: contracts/ubiquistick/package.json [hunk 6]
```diff
@@ -5,7 +5,7 @@
   "main": "index.js",
   "scripts": {
     "clean": "hardhat clean",
-    "build": "TS_NODE_TRANSPILE_ONLY=1 hardhat compile",
+    "build": "TS_NODE_TRANSPILE_ONLY=1 yarn hardhat compile",
```
Comment (0x4007) [inline contracts/ubiquistick/package.json:8]: I was experimenting with this, not sure if I'm to blame for this line, but curious to know if this is required or not?

File: package.json [hunk 7]
```diff
@@ -2,38 +2,33 @@
...
   "license": "MIT",
   "scripts": {
-    "ape": "run-s init:env make start",
-    "make": "run-s _contracts:install _contracts:build",
-    "start": "run-p _start:*",
-    "init:env": "cp .env.example .env",
-    "killscript": "kill `ps | grep dev-chain-init.sh | grep -v grep | awk '{ print $1 }'`",
-    "_start:chain": "./build-scripts/dev-chain-init.sh",
-    "_start:ui": "next dev",
+    "ape": "run-s install-env install-contracts dev",
```
Comment (0x4007) [inline package.json:5]: I will eventually want to make formal/standard script names; perhaps `yarn start` could be more appropriate

File: pages/index.tsx [hunk 8]
```diff
@@ -1,9 +1,8 @@
...
-
-export default PriceStabilization;
 import FullDeployment from "../fixtures/ubiquity-dollar-deployment.json";
 
 export const ADDRESS = {
   MANAGER: FullDeployment.contracts.UbiquityAlgorithmicDollarManager.address,
   DEBT_COUPON_MANAGER: FullDeployment.contracts.DebtCouponManager.address,
 };
+
+export { default as default } from "./price-stabilization";
```
Comment (0x4007) [inline pages/index.tsx:8]: default as default? lol
